### PR TITLE
fix: Resolve timezone bugs

### LINKED ISSUE #16: Availability bug, no availability for TODAY
## Expected Behavior
Available slots for TODAY extending from NOW until 11PM PST

## Observed Behavior
No more available openings for today despite those hours being open as defined by DEFAULT_WORKDAY

## Screenshot
IMG_1234

### LINKED ISSUE #17: Direct user to first appointment bug
## Expected Behavior
Loading the base website `/` should direct the user to the first available day of appointments, eg Friday

## Observed Behavior 
During certain time windows the application loads `/` and directs the user to the following day, eg Saturday

## Details
This is likely because the useEffect hook isn't consdering timezone when offering suggestions of date.

```js
// index.ts
  useEffect(() => {
    if (!selectedDate && slots.length > 0) {
      dispatch({
        type: "SET_SELECTED_DATE",
        payload: Day.dayFromDate(slots[0].start), // <-- Doesn't take into account frontend timezone
      })
    }
  }, [])
```

## Screenshots
image
<details>
<summary>View Screenshots</summary>
image

</details>

### PR DESCRIPTION
**Pull request by Spiteless**
## Overview

A few tweaks to get the availability and timezones working properly.

* Force interval Date objects to use UTC when generated via `"Etc/GMT"` timezone
* Switch DayButton isDisabled to track if the offers array has available appointemnts
* Create another function to generate a date string from the user's local timezone
  * This resolves issues of appointments being shunted to other dates based on UTC vs User local timezone
  * This might be better placed in helpers.ts. I put this in it's own file in `./lib`

Fixes #16 
Fixes #17

### CODE REVIEW

File: lib/locale.ts [hunk 1]
```diff
@@ -0,0 +1,16 @@
+/**
+ * Returns a string representation of the Date object
+ * in 'YYYY-MM-DD' format, respecting the user's timezone.
+ *
+ * @returns {string} The formatted date string.
+ */
+export default function localeDayString(date: Date): string {
+  const dateOptions: Intl.DateTimeFormatOptions = {
```
Comment (timfee) [inline lib/locale.ts:8]: Thanks for the PR. Using 'en-ca' _does_ prevent different locales from producing unexpected date representations, but I'd rather avoid hard-coding values like this. Maybe a date-fns-tz function that explicitly produces YYYY-mm-dde?

**Comment by Spiteless** [comment]
Updated to:

```ts
import { format } from 'date-fns-tz'

/**
 * Returns a string representation of the Date object
 * in 'YYYY-MM-DD' format, respecting the user's timezone.
 *
 * @returns {string} The formatted date string.
 */
export default function localeDayString(date: Date): string {
  const dateOptions: Intl.DateTimeFormatOptions = { 
    timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone 
  };
  const dateString: string = format( date, 'yyyy-MM-dd', { timeZone: dateOptions.timeZone } )
  return dateString
}
```

Is that more what you're looking for?

**Comment by timfee** [comment]
> Updated to:
> 
> ```ts
> import { format } from 'date-fns-tz'
> 
> /**
>  * Returns a string representation of the Date object
>  * in 'YYYY-MM-DD' format, respecting the user's timezone.
>  *
>  * @returns {string} The formatted date string.
>  */
> export default function localeDayString(date: Date): string {
>   const dateOptions: Intl.DateTimeFormatOptions = { 
>     timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone 
>   };
>   const dateString: string = format( date, 'yyyy-MM-dd', { timeZone: dateOptions.timeZone } )
>   return dateString
> }
> ```
> 
> Is that more what you're looking for?

I'm _99%_ sure, and will double check when I have time later. 

In essence, I was looking to keep it self-evident that the format in the URL string (regardless of how the user's _locale_ parses dates) is yyyy-MM-dd **while** respecting the timezone to address the bug you've squashed.

I think this helps make it clear (esp. for when we need to `parse` the date in the future) what the format actually looks like. Thanks!

**Comment by Spiteless** [comment]
🥳🥳🥳
